= terminology

openEHR reference model terminology, and artefacts for binding or using standard terminologies.

== Reporting issues or requesting new terms
*Any issues, change requests or problem reports, including requests for new terms should be posted via the https://openehr.atlassian.net/projects/SPECRM[openEHR Specifications JIRA Tracker]*


== RELEASE-2.0.0

This release establishes a more solid baseline for terminology list governance.

Some of the https://openehr.atlassian.net/browse/SPECPR-95?jql=project%20%3D%20SPECPR%20AND%20component%20%3D%20%22openEHR%20Terminology%22[outstanding terminology SPECPRs] have been fixed here, other fixes will be applied in later commits.

The the Git Tag mechanism will be used to formally label Releases e.g. RELEASE-2.0.0, using the semver.org mechanism adopted by the clinical models.

This branch will be RELEASE-2.0.0, reflecting the breaking changes in the file format and content.

**19 Feb 2017**

== Changes from RELEASE-1.0.0

* Added Japanese translation.


**17 June 2016-06**

== Changes from RELEASE-1.0.0

Based on java-lib terminology files - https://openehr.atlassian.net/browse/SPECPR-25[SPECPR-25]

* New directory structure
* Removed mediatypes from openEHR internal terminology, now carried as external terminology
* Added mediatypes https://openehr.atlassian.net/browse/SPECPR-97[SPECPR-97]
* Added Khmer language https://openehr.atlassian.net/browse/SPECPR-24[SPECPR-24]
* Added XML schema for Terminology XML files https://openehr.atlassian.net/browse/SPECPR-3[SPECPR-3]
